# Generated by Django 4.2.7 on 2023-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0015_alter_cisco_config_result_id_alter_cisco_output_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciscoDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.CharField(default='20', max_length=25)),
                ('success', models.CharField(default='True', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ciscoconfig',
            name='timestamp',
            field=models.CharField(default=1699335408.948062, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1699335408.945486, max_length=30),
        ),
    ]
