# Generated by Django 4.2.7 on 2023-11-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztest_ztest1', '0016_ciscodna_alter_ciscoconfig_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciscodna',
            name='output',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ciscoconfig',
            name='timestamp',
            field=models.CharField(default=1699350943.873398, max_length=30),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='timestamp',
            field=models.CharField(default=1699350943.871147, max_length=30),
        ),
    ]
